import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { GymHeaderComponent } from './gym-header.component';

@Component({
  selector: 'app-gym-landing', standalone: true, imports: [RouterLink, GymHeaderComponent],
  template: `<app-gym-header/><main class="gym-page"><section class="hero"><div class="hero-copy"><p class="eyebrow">ACE GYM · TRAIN WITH PURPOSE</p><h1>Built for your<br><em>next level.</em></h1><p>Strength, consistency and a community that moves with you. Make every session count at ACE Gym.</p><div class="actions"><a class="button" routerLink="/gym/login">Member sign in <span>↗</span></a><a class="text-link" href="#experience">Explore the gym ↓</a></div><small class="demo-note">Gym member experience · interactive UI preview</small></div><div class="logo-placeholder" aria-label="ACE Gym shield logo asset not available"><span>ACE GYM LOGO</span><small>Waiting for supplied shield artwork</small></div></section><section id="experience" class="experience"><div class="section-heading"><p class="eyebrow">YOUR ROUTINE, YOUR MOMENTUM</p><h2>Show up. <em>Level up.</em></h2><p>A focused space to build habits that last.</p></div><div class="feature-grid"><article><span class="feature-icon">01</span><h3>Train with intention</h3><p>Space to focus on your movement, strength and progress.</p></article><article><span class="feature-icon">02</span><h3>Track your consistency</h3><p>Keep an eye on your visits and celebrate the streaks you build.</p></article><article><span class="feature-icon">03</span><h3>Make every visit count</h3><p>Capture your workout notes and see your membership at a glance.</p></article></div></section><section class="member-cta"><div><p class="eyebrow">YOUR ACE MEMBERSHIP</p><h2>One session at a time.</h2><p>Members can review their progress and keep a record of every visit.</p></div><a class="button" routerLink="/gym/login">Open member portal <span>↗</span></a></section></main><footer class="gym-footer"><span>ACE GYM · SAMPLE UI</span><a routerLink="/turf">Explore ACE Turf ↗</a></footer>`,
  styles: [`.gym-page{background:#fff;color:#0B2E22;font-family:Arial,Helvetica,sans-serif}.hero{min-height:500px;max-width:1280px;padding:58px clamp(24px,7vw,90px);margin:auto;display:grid;grid-template-columns:1fr 1fr;gap:36px;align-items:center}.eyebrow{font-size:.68rem;letter-spacing:.14em;font-weight:800;color:#0B2E22;margin:0 0 18px}.hero h1,.section-heading h2,.member-cta h2{font-size:clamp(3rem,6vw,5.2rem);line-height:.96;letter-spacing:-.04em;margin:0;font-weight:850}.hero h1 em,.section-heading h2 em{color:#0B2E22;font-style:normal}.hero-copy>p:not(.eyebrow){max-width:440px;color:#4d6256;line-height:1.7;margin:22px 0}.actions{display:flex;align-items:center;gap:24px;flex-wrap:wrap}.button{display:inline-flex;gap:24px;align-items:center;padding:14px 17px;background:#FFD52A;color:#0B2E22;font-size:.72rem;font-weight:800;text-decoration:none;text-transform:uppercase;letter-spacing:.05em}.text-link{color:#0B2E22;font-size:.75rem;font-weight:700;text-decoration:none}.demo-note{display:block;color:#66776d;font-size:.66rem;margin-top:22px}.logo-placeholder{min-height:320px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:9px;background:#0B2E22;color:#FFD52A;text-align:center}.logo-placeholder span{font-weight:800;font-size:.8rem;letter-spacing:.16em}.logo-placeholder small{color:#fff;font-size:.68rem}.experience{padding:70px clamp(24px,7vw,90px);background:#f6f7f4}.section-heading{text-align:center;margin-bottom:34px}.section-heading h2{font-size:clamp(2.5rem,4vw,3.8rem)}.section-heading>p:last-child{color:#5f7065;margin-top:12px}.feature-grid{max-width:1080px;margin:auto;display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.feature-grid article{padding:24px;background:#fff;border:1px solid #e1e6e1}.feature-icon{display:grid;place-items:center;width:34px;height:34px;background:#FFD52A;color:#0B2E22;font-weight:800;font-size:.7rem}.feature-grid h3{margin:20px 0 9px;font-size:1.05rem}.feature-grid p,.member-cta p:not(.eyebrow){color:#596b60;font-size:.84rem;line-height:1.65;margin:0}.member-cta{padding:50px clamp(24px,7vw,90px);background:#0B2E22;color:#fff;display:flex;align-items:center;justify-content:space-between;gap:25px}.member-cta .eyebrow{color:#FFD52A}.member-cta h2{font-size:clamp(2rem,3.5vw,3.1rem);margin:0 0 11px}.member-cta p:not(.eyebrow){color:#fff;max-width:480px}.gym-footer{display:flex;justify-content:space-between;padding:18px clamp(24px,7vw,90px);background:#0B2E22;color:#fff;font-size:.64rem;letter-spacing:.08em}.gym-footer a{color:#FFD52A;text-decoration:none}@media(max-width:760px){.hero{grid-template-columns:1fr;padding-top:42px}.logo-placeholder{min-height:230px}.feature-grid{grid-template-columns:1fr}.member-cta{align-items:flex-start;flex-direction:column}.hero h1{font-size:3.35rem}}`]
})
export class GymLandingComponent {}
