import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../core/services/auth.service';
import { PermissionService } from '../core/permission.service';
import { TurfPricing } from '../shared/models/arena.models';

@Component({
  standalone: true, selector: 'app-portal', imports: [CommonModule, FormsModule, RouterLink],
  template: `<main class="portal"><header><a routerLink="/" class="brand">ACE <small>MULTISPORT ARENA</small></a><a routerLink="/turf">Book turf</a></header>
    @if (kind === 'login' || kind === 'register') {
      <section class="form-card"><p class="eyebrow">{{ kind === 'login' ? 'WELCOME BACK' : 'JOIN THE ARENA' }}</p><h1>{{ kind === 'login' ? 'Sign in' : 'Create account' }}</h1><p class="muted">Secure sign-in will be enabled when the authentication API is connected.</p>
      <form (ngSubmit)="submitAuth()"><label *ngIf="kind === 'register'">Name<input [(ngModel)]="name" name="name" required autocomplete="name"></label><label>Email<input [(ngModel)]="email" name="email" type="email" required autocomplete="email"></label><label>Password<input [(ngModel)]="password" name="password" type="password" required autocomplete="current-password"></label><button class="primary" type="submit">{{ kind === 'login' ? 'Sign in' : 'Create account' }}</button></form><p class="error" *ngIf="message">{{ message }}</p><a [routerLink]="kind === 'login' ? '/register' : '/login'">{{ kind === 'login' ? 'New to ACE? Register' : 'Already registered? Sign in' }}</a></section>
    } @else if (kind === 'my-bookings') {<section><p class="eyebrow">CUSTOMER AREA</p><h1>My bookings</h1><p class="muted">Your booking history will appear here once connected to the booking API.</p><div class="notice">No bookings loaded. Connect GET /api/bookings/mine to show your upcoming and previous bookings.</div><a class="primary link-button" routerLink="/turf">Explore available turf</a></section>
    } @else if (kind === 'confirmation') {<section class="form-card"><p class="eyebrow">BOOKING STATUS</p><h1>Confirmation pending</h1><p class="muted">This page will show a confirmed booking only after the backend validates availability and payment.</p><div class="notice">No booking ID or payment status is available. Do not treat this screen as a booking or payment confirmation.</div><a class="primary link-button" routerLink="/my-bookings">View my bookings</a><a class="secondary link-button" routerLink="/">Back to home</a></section>
    } @else {<section><p class="eyebrow">ACE OPERATIONS</p><h1>Admin dashboard</h1><p class="muted">Staff tools are subject to server authorization. Preview figures below are illustrative only.</p><nav class="tabs"><a routerLink="/admin">Overview</a><a routerLink="/admin/bookings">Bookings</a><a routerLink="/admin/slots">Turf slots</a><a routerLink="/admin/pricing">Pricing</a><a routerLink="/admin/users">Users</a></nav>
      @if (kind === 'pricing') {<article class="card"><h2>Pricing management</h2><p class="muted">Values below are an unsaved UI preview, not live pricing.</p><form (ngSubmit)="savePricing()"><label>Weekday price<input type="number" min="0" [(ngModel)]="pricing.weekdayPrice" name="weekday"></label><label>Weekend price<input type="number" min="0" [(ngModel)]="pricing.weekendPrice" name="weekend"></label><label>Currency<input [(ngModel)]="pricing.currency" name="currency"></label><button class="primary" type="submit">Save changes</button></form><p class="error">{{ message }}</p></article>}
      @else if (kind === 'admin-bookings') {<article class="card"><h2>Bookings</h2><p class="muted">No live bookings loaded. Connect GET /api/admin/bookings.</p><label>Search bookings<input placeholder="Name, phone, booking ID" [(ngModel)]="search" name="search"></label><p>Filters: <button class="secondary">Today</button> <button class="secondary">Future</button> <button class="secondary">All</button></p></article>}
      @else if (kind === 'admin-slots') {<article class="card"><h2>Turf slot management</h2><p class="muted">Availability and reservations require server-backed slot locking.</p><label>Date<input type="date" [(ngModel)]="date" name="date"></label><div class="notice">Illustrative availability only. A server must lock selected slots atomically before confirmation.</div><form (ngSubmit)="reserveOffline()"><label>Available sample slots<select multiple [(ngModel)]="reservationSlots" name="slots"><option value="18:00">6:00–7:00 PM</option><option value="19:00">7:00–8:00 PM</option><option value="20:00">8:00–9:00 PM</option></select></label><label>Customer name<input [(ngModel)]="customerName" name="customer" required></label><label>Phone number<input [(ngModel)]="phone" name="phone" type="tel" required></label><label>Notes<input [(ngModel)]="notes" name="notes"></label><button class="primary" type="submit">Reserve offline</button></form><p class="error">{{ message }}</p></article>}
      @else if (kind === 'admin-users') {<article class="card"><h2>Users</h2><p class="muted">User search and role management require the protected users API.</p></article>}
      @else {<div class="stats"><article class="card"><small>Today's bookings</small><strong>—</strong></article><article class="card"><small>Available slots</small><strong>—</strong></article><article class="card"><small>Reserved slots</small><strong>—</strong></article><article class="card"><small>Revenue</small><strong>—</strong></article></div><article class="card"><h2>Operations overview</h2><p class="muted">Dashboard metrics are not connected. No placeholder figures are presented as real data.</p><a routerLink="/admin/bookings">Manage bookings →</a></article>}
    </section>}</main>`,
  styles: [`:host{display:block;min-height:100vh;background:#141719;color:#f2f4f2;font-family:Arial,sans-serif}.portal{max-width:1180px;margin:auto;padding:0 clamp(20px,6vw,84px) 64px}header{height:76px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #303739}header a{color:inherit;text-decoration:none}.brand{font-weight:900;letter-spacing:.08em}.brand small{display:block;font-size:.52rem;margin-top:4px}.portal section{padding:56px 0}.eyebrow{font-size:.7rem;color:#39dc84;letter-spacing:.16em;font-weight:bold}h1{font-size:clamp(2.6rem,7vw,5rem);margin:12px 0}h2{margin-top:0}.muted{color:#aeb8b5;line-height:1.6}.form-card,.card{background:#1b2023;border:1px solid #303a3c;border-radius:10px;padding:24px}.form-card{max-width:520px;margin:54px auto}.form-card form,.card form{display:grid;gap:16px;margin:24px 0}.portal label{display:grid;gap:7px;color:#bcc5c1;font-size:.86rem}.portal input{min-height:48px;padding:12px;background:#111719;border:1px solid #47514e;border-radius:5px;color:white;font:inherit}.primary,.secondary{display:inline-flex;align-items:center;justify-content:center;min-height:48px;padding:0 20px;border:0;border-radius:5px;background:#39dc84;color:#102117;font-weight:800;text-decoration:none;cursor:pointer}.secondary{background:#293431;color:#dce5df}.link-button{margin-top:18px}.error{color:#ffc1a7}.notice{margin:20px 0;padding:16px;background:#202a25;border:1px solid #39483e;color:#c9d2cd;line-height:1.55}.tabs{display:flex;gap:10px;flex-wrap:wrap;margin:28px 0}.tabs a{color:#d5ddd9;padding:12px 15px;border:1px solid #3b4541;border-radius:5px;text-decoration:none}.tabs a:hover{border-color:#39dc84}.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-bottom:18px}.stats small{color:#acb7b1}.stats strong{display:block;font-size:2.2rem;margin-top:12px}@media(max-width:700px){.portal section{padding-top:35px}.stats{grid-template-columns:1fr 1fr}.form-card{margin:32px 0}.card{padding:18px}}@media(max-width:390px){.stats{grid-template-columns:1fr 1fr}.tabs{gap:6px}.tabs a{font-size:.82rem;padding:11px}}`]
})
export class PortalComponent {
  private readonly router = inject(Router);
  readonly auth = inject(AuthService);
  readonly permissions = inject(PermissionService);
  readonly kind = this.routeKind();
  name = ''; email = ''; password = ''; message = ''; search = ''; date = ''; reservationSlots: string[] = []; customerName = ''; phone = ''; notes = '';
  pricing: TurfPricing = { turfId: 'ace-turf', weekdayPrice: 0, weekendPrice: 0, currency: 'INR' };
  private routeKind(): string { const path = this.router.url.split('?')[0]; if (path === '/login' || path === '/register') return path.slice(1); if (path === '/my-bookings') return 'my-bookings'; if (path === '/admin/pricing') return 'pricing'; if (path === '/admin/bookings') return 'admin-bookings'; if (path === '/admin/slots') return 'admin-slots'; if (path === '/admin/users') return 'admin-users'; return 'admin'; }
  async submitAuth(): Promise<void> { try { if (this.kind === 'register') await this.auth.register(this.name, this.email, this.password); else await this.auth.login(this.email, this.password); this.message = ''; } catch (e) { this.message = e instanceof Error ? e.message : 'Authentication unavailable.'; } }
  async savePricing(): Promise<void> { this.message = 'Pricing API is not connected. No changes were saved.'; }
  reserveOffline(): void { this.message = 'Admin reservation API is not connected. No slots were reserved.'; }
}
